# Custom Language File for Launcher Customizer

[ejs.app]
title = "Kirkoc Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kirkoc"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/W9yEEs4"

[ejs.settings]
sourceGithubLink = "https://github.com/Kirkoc/Launcher"
supportLink = "https://github.com/Kirkoc/Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME"
welcomeDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Molestie a iaculis at erat pellentesque adipiscing commodo. Suscipit tellus mauris a diam maecenas. Vestibulum sed arcu non odio euismod lacinia. Fermentum posuere urna nec tincidunt. Rhoncus est pellentesque elit ullamcorper dignissim cras. Faucibus scelerisque eleifend donec pretium. Elementum sagittis vitae et leo duis. Dictum at tempor commodo ullamcorper a lacus vestibulum. Libero enim sed faucibus turpis in eu mi bibendum neque."
welcomeDescCTA = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed posuere quam."
