name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash
      
      # Upload artifacts with OS specific names
      - name: Upload Build Artifacts - macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: electron-builds-macos
          path: ./dist/*.dmg

      - name: Upload Build Artifacts - Ubuntu
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: electron-builds-linux
          path: ./dist/*.AppImage

      - name: Upload Build Artifacts - Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: electron-builds-windows
          path: ./dist/*.exe
